### ISSUE TITLE
Syntax Error when importing pygicord module due to trailing comma

### ISSUE THREAD

**Issue by ljdb** [davidetacchini/pygicord#1]
**Describe the bug**
When trying to import the module in Python, a syntax error is returned.

**To Reproduce**
1. Open python shell
2. Run ```import pygicord```
3. Syntax error is returned:

```
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygicord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\daily\AppData\Local\Programs\Python\Python35\lib\site-packages\pygicord\__init__.py", line 76
    ):
    ^
SyntaxError: invalid syntax
```

**Expected behavior**
The module should have been imported without any errors.

**Screenshots**
N/A - full error message is above.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

The problematic code is around lines 75-76:
```python
    def __init__(
        self,
        *,
        pages: Optional[Union[List[discord.Embed], discord.Embed]] = None,
        compact: bool = False,
        timeout: float = 90.0,
        has_input: bool = True,
    ):
```

When I remove the trailing comma, the syntax error disappears:
```python
    def __init__(
        self,
        *,
        pages: Optional[Union[List[discord.Embed], discord.Embed]] = None,
        compact: bool = False,
        timeout: float = 90.0,
        has_input: bool = True
    ):
```

**Comment by davidetacchini** [comment]
Hi @ljdb,
Pygicord only supports python 3.6 or above, you should consider upgrading your python version

**Comment by ljdb** [comment]
It's a bit of a shame though. Just removing this trailing comma the module runs perfectly well on python 3.5. But OK.

**Comment by davidetacchini** [comment]
Fine. Remember that you can always submit a pull request. Thanks for the info though!

**Comment by ljdb** [comment]
> Remember that you can always submit a pull request.
Fair point. But I see that you did a commit to fix this. It now works locally for me. 

Thanks for doing that!
