### ISSUE TITLE
Embed only responds to person who called it

### ISSUE THREAD

**Issue by h1n054ur** [davidetacchini/pygicord#2]
Hi, Ive been using your pagnitor for a project, its by far the easiest and most forward to use out of all the ones, so first of all great job!

One issue i have run into before deploying my bot is that the paginated embed only responds to the original person who called the command.

Is there anyway to make it so anybody can interact with it?

**Comment by davidetacchini** [comment]
Hi @h1n054ur,

Thanks! Yes it's possible. The only way I can think of it is by adding a new reaction to lock/unlock the embed to make it available for other people to use. I'll see what I can do. Meanwhile if you know how to do that, you can submit a pull request.

**Comment by h1n054ur** [comment]
@davidetacchini 

thank you for working on the update!!

**Comment by davidetacchini** [comment]
I've just submitted a new release (v0.5.0-alpha). Since it's an alpha, I'd like you (and others as well) to test it out by installing it directly via git:
```shell
pip install git+https://github.com/davidetacchini/pygicord
```
If you'll encount any issue don't hesitate to open a new one.
