### ISSUE TITLE
Custom Emotes for Paginator

### ISSUE THREAD

**Issue by ritik0ranjan** [davidetacchini/pygicord#3]
As you introduced, `has_lock` and `has_input`. Can you add something like custom Emotes for pagination, please? Native Discord Emotes kinda ugly

**Comment by davidetacchini** [comment]
Hi, custom emotes will be available in the next update. Thanks for suggesting.

**Comment by davidetacchini** [comment]
I've just released a new update which supports custom emojis. Pygicord has been completely refactored though. Thus, checkout the release notes to find out what's changed, or consult the README file.

**Comment by ritik0ranjan** [comment]
impressive. :tada:
