### ISSUE TITLE
Remove reactions

### ISSUE THREAD

**Issue by curation-bot-guy** [davidetacchini/pygicord#4]
It's a bit annoying to have to remove reactions manually every time. Ideally, the bot could remove reactions in a similar way to the paginator of [discord-pretty-help](https://github.com/stroupbslayen/discord-pretty-help).

**Comment by davidetacchini** [comment]
Hi, to be honest, I don't understand why you find it annoying. Whenever a reaction is removed, Pygicord will still execute the task that the reaction is related to. Furthermore, it's actually the most convenient way to do this. No permissions are required, as there's no need to remove a user's reaction, and it's faster to use.
